### ISSUE TITLE
在CoordinatorLayout中添加MultipleStatusView，内容无法居中

### ISSUE THREAD

**Issue by renygit** [qyxxjd/MultipleStatusView#10]
如题，CoordinatorLayout中第一个了控件是AppBarLayout，第二个是MultipleStatusView，MultipleStatusView中的子视图无法居中

**Comment by qyxxjd** [comment]
相关布局文件发出来看下

**Comment by renygit** [comment]
<android.support.design.widget.CoordinatorLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical">

                <android.support.design.widget.AppBarLayout...>
                <com.classic.common.MultipleStatusView
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    app:emptyView="@layout/view_state_empty_view"
                    app:errorView="@layout/view_state_error_view"
                    app:loadingView="@layout/view_state_loading_view"
                    app:multiState="@{viewModel.stateViewType}"
                    app:noNetworkView="@layout/view_state_no_network_view">
<////...>

大概是这样，我现在把MultipleStatusView移到最外层了，勉强能用。

**Comment by qyxxjd** [comment]
请参考：
- [列表页面示例](https://github.com/qyxxjd/MultipleStatusView/blob/master/app/src/main/res/layout/activity_list.xml)
- [列表 + 下拉刷新示例](https://github.com/qyxxjd/MultipleStatusView/blob/master/app/src/main/res/layout/activity_refresh.xml)
