### ISSUE TITLE
引用库报错，使用不了

### ISSUE THREAD

**Issue by Leu-Z** [qyxxjd/MultipleStatusView#14]
在实例代码中build显示以下错误：
`Error:Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.classic.common:multiple-status-view:1.4.
<a href="openFile:C:/Users/Leu/Desktop/MultipleStatusView-master/app/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:app@debug/compileClasspath&#39;: Could not resolve com.classic.common:multiple-status-view:1.4.">Show Details</a>`
在自己的代码中引用也出了类似的错。
网上搜索之后是这个原因：
http://www.jcodecraeer.com/a/anzhuokaifa/Android_Studio/2017/1026/8646.html
可是其他的库都是可以用的，就这个库不行。

**Comment by qyxxjd** [comment]
你的 `Android Studio` 版本多少？

**Comment by Leu-Z** [comment]
3.0.1

**Comment by qyxxjd** [comment]
<img width="1040" alt="wx20171123-181057 2x" src="https://user-images.githubusercontent.com/10043599/33167886-f7fafbba-d079-11e7-8f79-e5ad3bef544b.png">
切换到本地的 `Gradle` 版本试试

**Comment by Leu-Z** [comment]
可以了，引用你的库用3.0新的编译方式implementation 就可以了，暂时还不清楚是什么原因导致的冲突
