### ISSUE TITLE
切换布局的时候重叠了

### ISSUE THREAD

**Issue by zhaoxiuyu** [qyxxjd/MultipleStatusView#18]
为什么切换不同的布局，各个布局的内容都出现了，重叠了。

**Comment by qyxxjd** [comment]
1. 运行 `Demo` 程序看是否会出现重叠
2. 提供一些有效信息

**Comment by dreamlivemeng** [comment]
最近也遇到这个问题，我的问题是加载中视图的id没有设置为作者提供的id，所以导致重叠了。
