### ISSUE TITLE
这个地方,这样写是不是有点不合适,如果多次showempty 是不是会导致解析xml布局文件多次

### ISSUE THREAD

**Issue by meijingkang** [qyxxjd/MultipleStatusView#21]
https://github.com/qyxxjd/MultipleStatusView/blob/65c7912291c51efc1f92e725b78c5a084ad3aa0b/multiple-status-view/src/main/java/com/classic/common/MultipleStatusView.java#L117

这个地方,这样写是不是有点不合适,如果多次showempty 是不是会导致解析xml布局文件多次

**Comment by qyxxjd** [comment]
感谢你的反馈！这里非首次调用会存在多余的 `inflate`, 后面会进行修正。

**Comment by qyxxjd** [comment]
[v1.5.1](https://github.com/qyxxjd/MultipleStatusView/releases/tag/v1.5.1)
