### ISSUE TITLE
同一个页面中多次使用会互相干扰

### ISSUE THREAD

**Issue by yuhaoz** [qyxxjd/MultipleStatusView#25]
在同一个界面中会出现干扰问题，如下所示：
1.当我在页面中放入一个时，效果如下
![image](https://user-images.githubusercontent.com/13252122/49718534-5a4b2180-fc95-11e8-8001-cdde7ef18d74.png)

2.当放入两个时，效果如下
![image](https://user-images.githubusercontent.com/13252122/49718584-82d31b80-fc95-11e8-9dd9-e7903080278b.png)

这两个contentView的内容高度都是自适应的，高度值是不一样的，如果多次使用时，所有的contentView的高度都会和最后一个contentView的高度保持一致，而不是使用自己的高度，所以出现上面显示不全的现象。

**Comment by qyxxjd** [comment]
使用一个`MultipleStatusView`，多个数据源都获取到数据后，再一次性展示UI，这样处理会不会好一点

**Comment by yuhaoz** [comment]
@qyxxjd  已经处理好了，把内容放在里面，就不会互相干扰了，如下所示：

![image](https://user-images.githubusercontent.com/13252122/49848867-116ca780-fe12-11e8-93d7-76bac13b865f.png)
