### ISSUE TITLE
建议修改STATUS_CONTENT的值，或者设置mViewStatus的值为-1

### ISSUE THREAD

**Issue by HuJianChong** [qyxxjd/MultipleStatusView#27]
初始化时，mViewStatus默认值为0，和STATUS_CONTENT相同了。弄得我很难通过getViewStatus对比STATUS_CONTENT的值，来判断是否是赋值为STATUS_CONTENT，还是初始情况
![image](https://user-images.githubusercontent.com/7711020/50676363-f535e200-102e-11e9-8710-595be7284c29.png)

**Comment by qyxxjd** [comment]
下个版本修复，家里网太差，周一去公司了发个新版本
