### ISSUE TITLE
嵌套了官方的刷新刷新被阻拦了

### ISSUE THREAD

**Issue by 92dadazhou** [qyxxjd/MultipleStatusView#3]
如题.....真不知道大家有遇到吗

**Comment by qyxxjd** [comment]
把官方的刷新组件放在`contentView`试试

**Comment by 92dadazhou** [comment]
我就是放在哪里的，主页面可以，但是空页面上面的不能刷新

**Comment by qyxxjd** [comment]
当前视图为`contentView`有数据的情况，才可以使用刷新功能。`emptyView`你可以添加一个点击重试的`view`进行处理

**Comment by 92dadazhou** [comment]
如何调取emptyView的控件和点击事件

**Comment by qyxxjd** [comment]
你加下我QQ或微信：630404403，然后跟你详细解释
