### ISSUE TITLE
加载视图可以禁止触摸吗？

### ISSUE THREAD

**Issue by lindroy** [qyxxjd/MultipleStatusView#30]
作者你好，我在项目中遇到这样的需求：在空视图时也可以下拉刷新，所以MultipleStatusView是放在下拉刷新库里面的，但是这样话在加载视图时也可以下拉刷新，这样会频繁触发网络请求。所以可以在加载数据显示加载视图的时候禁止其他操作吗？

**Comment by qyxxjd** [comment]
是什么场景？把刷新控件放在内容视图里可行不？[类似于这个](https://github.com/qyxxjd/MultipleStatusView/blob/master/app/src/main/res/layout/content_refresh.xml)

**Comment by lindroy** [comment]
描述起来有点难……简单地说，就是在显示空视图时也可以下拉刷新，所以MultipleStatusView必须放在上拉加载和下拉刷新框架的里面（我用的是[SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout)），这样MultipleStatusView的所有视图都可以触发上拉加载和下拉刷新，但是loading视图显然不能再上拉和下拉了，这时应该禁止页面的任何操作。不过我目前通过其他方式实现了：就是loading时页面肯定是没有数据的，数据为空我就把上拉和下拉禁掉。你看看能不能实现，如果实在太麻烦就把这issue关掉吧。
