### ISSUE TITLE
显示内容视图，存在bug

### ISSUE THREAD

**Issue by xushaun** [qyxxjd/MultipleStatusView#32]
显示内容视图的时候，会将MultipleStatusView下的不在mOtherIds列表内的所有childView的visibale状态置为Visiable，如果原来视图有部分是需要隐藏的就会全部显示出来

**Comment by xushaun** [comment]
问题描述的是正确的

**Comment by qyxxjd** [comment]
请仔细阅读 [README](https://github.com/qyxxjd/MultipleStatusView/blob/master/README.md) **注意事项**部分

## 注意事项

> 必须按如下规则设置对应视图根节点的 `view id`，否则会导致试图重叠  
> 必须按如下规则设置对应视图根节点的 `view id`，否则会导致试图重叠  
> 必须按如下规则设置对应视图根节点的 `view id`，否则会导致试图重叠  

#### 1. 如果使用自定义属性
```
app:emptyView="@layout/..."
app:errorView="@layout/..."
app:loadingView="@layout/..."
app:noNetworkView="@layout/..."
```
需要设置：

- 加载中视图的id必须为：`loading_view`
- 空视图的id必须为：`empty_view`
- 错误视图的id必须为：`error_view`
- 无网络视图的id必须为：`no_network_view`
- 自定义提示文本的id必须为：`status_hint_content`


#### 2. 如果需要点击某个 `view` 进行重试, 需要设置:

- 空视图内对应的view id：`empty_retry_view`
- 错误视图内对应的view id：`error_retry_view`
- 无网络视图内对应的view id：`no_network_retry_view`
