### ISSUE TITLE
能不能做到在同一个视图动态设置提示文案

### ISSUE THREAD

**Issue by lucky-you** [qyxxjd/MultipleStatusView#36]
实际开发中，很多空视图界面是一样的，只是提示文案信息不同，能不能做到动态设置提示文案信息，这样就不需要每次都去创建空视图了。

**Comment by qyxxjd** [comment]
See [MultipleStatusView v1.7](https://github.com/qyxxjd/MultipleStatusView/releases/tag/v1.7)
