### ISSUE TITLE
关于实现思路

### ISSUE THREAD

**Issue by ysmintor** [qyxxjd/MultipleStatusView#5]
好早前看过一次代码，就是viewgroup添加几个view,再去判断对应的状态，其它隐藏。
显然又加了一个层次，我考虑能否在Activity或者Fragment里面用代码依据对应的网络请求动态地去改变window的内容，不必这样一个层次，作者有时间可以讨论下。

**Comment by qyxxjd** [comment]
你的思路完全可行，和本库的原理也是一样的。

**Comment by ysmintor** [comment]
本库应该是多了一个层次，是吧ContentView放在一个viewgroup里面，同时保存了几个状态的页面。我想是在对应状态时才inflate对应布局。只是对decorview这块不太了解。

**Comment by qyxxjd** [comment]
是的，本库只是一种比较简单的实现方式
