### ISSUE TITLE
无法获取点击事件

### ISSUE THREAD

**Issue by wbSuperMan** [qyxxjd/MultipleStatusView#6]
在节点下面添加类似recyclerview的控件，在错误界面无法监听到重新加载的回掉

**Comment by qyxxjd** [comment]
把相关的 `Layout` 文件发出来看看

**Comment by wbSuperMan** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent" 
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="@color/common_bg_color"
    android:orientation="vertical">
    <include layout="@layout/common_titlebar"/>
    <com.classic.common.MultipleStatusView android:layout_width="match_parent"
                                      android:id="@+id/state_layout"
                                      android:layout_height="match_parent">
        <android.support.v7.widget.RecyclerView android:id="@+id/recycle"
                                                android:layout_width="match_parent"
                                                android:layout_height="match_parent">

        </android.support.v7.widget.RecyclerView>
    </com.classic.common.MultipleStatusView>

</LinearLayout>

**Comment by black1991** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="@color/common_bg_color"
    android:orientation="vertical">
    <include layout="@layout/common_titlebar"/>
    <com.classic.common.MultipleStatusView android:layout_width="match_parent"
                                      android:id="@+id/state_layout"
                                      android:layout_height="match_parent">
        <android.support.v7.widget.RecyclerView android:id="@+id/recycle"
                                                android:layout_width="match_parent"
                                                android:layout_height="match_parent">

        </android.support.v7.widget.RecyclerView>
    </com.classic.common.MultipleStatusView>

</LinearLayout>

**Comment by qyxxjd** [comment]
你写的不对，参考以下的代码：

#### **注意 id**
#### **注意 id**
#### **注意 id**

```
<com.classic.common.MultipleStatusView
    android:id="@+id/main_multiplestatusview"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:errorView="@layout/custom_error_view" >

    <android.support.v7.widget.RecyclerView 
        android:id="@+id/content_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</com.classic.common.MultipleStatusView>
```

`custom_error_view.xml`

```
<RelativeLayout
    android:id="@+id/error_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ImageView
        android:id="@+id/error_retry_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:src="@mipmap/ic_error"
        />

</RelativeLayout>
```
