### ISSUE TITLE
我设置了id跟demo一样的怎么点击试图重试没有用

### ISSUE THREAD

**Issue by wuyang049679** [qyxxjd/MultipleStatusView#7]

**Comment by qyxxjd** [comment]
相关布局文件发出来看下

**Comment by qyxxjd** [comment]
`demo` 示例:

- [简单布局](https://github.com/qyxxjd/MultipleStatusView/blob/master/app/src/main/res/layout/activity_simple.xml)
- [简单布局2](https://github.com/qyxxjd/MultipleStatusView/blob/master/app/src/main/res/layout/activity_simple2.xml)
- [设置自定义视图](https://github.com/qyxxjd/MultipleStatusView/blob/master/app/src/main/java/com/classic/common/simple/CustomActivity.java)
- [列表页面](https://github.com/qyxxjd/MultipleStatusView/blob/master/app/src/main/res/layout/activity_list.xml)
- [列表 + 下拉刷新](https://github.com/qyxxjd/MultipleStatusView/blob/master/app/src/main/res/layout/activity_refresh.xml)
