### ISSUE TITLE
一点改进建议

### ISSUE THREAD

**Issue by mzeht** [qyxxjd/MultipleStatusView#8]
根据mContentView = findViewById(R.id.content_view);去设置内容视图有点不便，用起来还得把内嵌视图最外层命名为content_view，繁琐切容易重复，可以考虑内嵌视图只支持一个子视图，然后mContentView = this.getChildAt(0);去处理

**Comment by qyxxjd** [comment]
如果有多个子内容视图，就不能使用 `getChildAt(0)` 来处理，这两天空了我优化一下

**Comment by mzeht** [comment]
只支持一个子视图应该是比较好的 没用这个多布局项目的直接把布局粘到内部就好了 不用还写id content_view

**Comment by qyxxjd** [comment]
请参考： [MultipleStatusView v1.3](https://github.com/qyxxjd/MultipleStatusView/blob/master/multiple-status-view/src/main/java/com/classic/common/MultipleStatusView.java)
